Add random de/serialize testing of all LSP types
Random testing with FsCheck of all LSP types.
Tests: `(o |> serialize |> deserialize) = o`

Note: Success just means object can do roundtrip to json and back again without exceptions.
It doesn't mean it gets serialized to the correct json representation!
And additional: is random testing -> there might be still a case that throws exception, but didn't get tested.  
And of course: not real-world-looking data

Note: New LSP types get automatically picked up when added to `Ionide.LanguageServerProtocol.Types` (`./src/Types.fs`).
Exception: Type Abbreviations get erased and cannot be picked up at runtime via reflection -> Must be manual added to tests (in `tests\Shotgun.fs`, start of `tests`)

Note: Checking new type usually just work. But sometimes it requires some additional handling:
* FsCheck cannot generate type (for example recursive types) -> requires custom Generator (see `Gen` in `tests\Shotgun.fs`)
* Type doesn't use structural equality -> `Expecto.equal` fails even when same content (for example case with `Dictionary` (in field with `JsonExtensionDataAttribute`) -> Requires replacing all Dictionaries with `Map` with same content for comparison)
  * Best stick to "normal" F# types, lists, arrays, `Map`s